title : Videos

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: videos
destination: videos

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10
paginate_path: "/blog/page:num"

production_url : http://videos.apievangelist.com

BASE_PATH : http://videos.apievangelist.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
